name: "IBM Login"
description: "login into IBM Cloud"
inputs:
  token: 
    description: "The token to login"
    required: true
  url: 
    description: "The url to connect into IBM Cloud"
    required: false
  region: 
    description: "Region name, for example 'us-south' or 'eu-gb'"
    required: true
  resourcegroup: 
    description: "Resource group ID"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.url }}
    - ${{ inputs.region }}
    - ${{ inputs.resourcegroup }}
branding:
  color: 'green'
  icon: 'at-sign'